services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "21000:21000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "21001:21001"
    volumes:
      - ./backend/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
