"""add session_tokens table

Revision ID: 43d18bb7912d
Revises: 26e2510e92fd
Create Date: 2026-03-05 13:28:14.666544
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d18bb7912d'
down_revision: Union[str, None] = '26e2510e92fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('imp_user_id', sa.Integer(), nullable=True),
    sa.Column('imp_username', sa.String(length=255), nullable=True),
    sa.Column('imp_name', sa.String(length=255), nullable=True),
    sa.Column('imp_role', sa.String(length=20), nullable=True),
    sa.Column('imp_advisor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_tokens_token'), 'session_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_tokens_token'), table_name='session_tokens')
    op.drop_table('session_tokens')
    # ### end Alembic commands ###
