"""add advisors table and advisor_id to documents

Revision ID: 98b1bb4625d6
Revises: 73e752491203
Create Date: 2026-02-17 15:17:07.835166
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b1bb4625d6'
down_revision: Union[str, None] = '73e752491203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_name', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_advisor_name'), 'advisors', ['advisor_name'], unique=True)
    op.add_column('documents', sa.Column('advisor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_advisor_id'), 'documents', ['advisor_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'advisors', ['advisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_advisor_id'), table_name='documents')
    op.drop_column('documents', 'advisor_id')
    op.drop_index(op.f('ix_advisors_advisor_name'), table_name='advisors')
    op.drop_table('advisors')
    # ### end Alembic commands ###
